apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "redis-ha.name" . }}-sentinel-svc
    role: service
{{ include "redis-ha.labels.standard" . | indent 4 }}
  name: {{ template "redis-ha.fullname" . }}-sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
