apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "redis-ha.fullname" . }}
  labels:
    redis-node: "true"
{{ include "redis-ha.labels.standard" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas.slave }}
  template:
    metadata:
      labels:
        name: redis
        role: replica
{{ include "redis-ha.labels.standard" . | indent 8 }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis_image }}"
        resources:
{{ toYaml .Values.resources.slave | indent 10 }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
      - name: data
      {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "redis-ha.fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
