apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ template "redis-ha.name" . }}
    role: service
{{ include "redis-ha.labels.standard" . | indent 4 }}
  name: {{ template "redis-ha.fullname" . }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    redis-node: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
